version: '3.4'

services:
  ApiGateway:
    image: ahmedezzatg/learninglantern.apigateway
    build:
      context: .
      dockerfile: ApiGateway/LearningLantern.ApiGateway/Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
  
  TodoList:
    image: ahmedezzatg/learninglantern.todolist
    build:
      context: .
      dockerfile: TodoList/LearningLantern.TodoList/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80

  Calendar:
    image: ahmedezzatg/learninglantern.calendar
    build:
      context: .
      dockerfile: Calendar/LearningLantern.Calendar/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
  
  Video:
    image: ahmedezzatg/learninglantern.video
    build:
      context: .
      dockerfile: Video/LearningLantern.Video/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
        
  TextLesson:
    image: ahmedezzatg/learninglantern.textlesson
    build:
      context: .
      dockerfile: TextLesson/LearningLantern.TextLesson/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    
  Admin:
    image: ahmedezzatg/learninglantern.admin
    build:
      context: .
      dockerfile: Admin/LearningLantern.Admin/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80