version: '3.4'

services:
  ApiGateway:
    image: learninglantern.apigateway
    build:
      context: .
      dockerfile: ApiGateway/LearningLantern.ApiGateway/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  TodoList:
    image: learninglantern.todolist
    build:
      context: .
      dockerfile: TodoList/LearningLantern.TodoList/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  Calendar:
    image: learninglantern.calendar
    build:
      context: .
      dockerfile: Calendar/LearningLantern.Calendar/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    
  Video:
    image: learninglantern.video
    build:
      context: .
      dockerfile: Video/LearningLantern.Video/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  
  TextLesson:
    image: learninglantern.textlesson
    build:
      context: .
      dockerfile: TextLesson/LearningLantern.TextLesson/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  
  Admin:
    image: learninglantern.admin
    build:
      context: .
      dockerfile: Admin/LearningLantern.Admin/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80